### ISSUE TITLE
Add support for local configuration customization

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-backend#10]
Currently, we have a `config/config.js`, that reads environment variables for some configuration parameters, and falls back to default values.

This is a nice approach. However it might be cumbersome to maintain environment variables to override default config parameters e.g. in the test environment.

My suggestion is:

 * create a `config/config.<instance>.js` local configuration file which is on gitignore, and instance corresponds to the actual environment, e.g. prod, test, dev.
   This should hold the environment-specific configuration data, e.g. database host name or credentials
 * `config/config.js`
    * should hold only default configuration, that is never modified locally, thus it is easy to update from the repository with default config for new features
    * should never contain sensitive data like actual passwords for some services
    * should read `config.<instance>.js` and use values provided there
    * if a value is not overridden in the instance config, shoul fall back to some reasonable default (as it does currently)
 * it is to be determined how to specify the the instance name to use

Subtasks:

- [x] design how to specify the instance name to use
- [x] add support for local configuration

**Comment by Kisfejes** [comment]
Resolved in https://github.com/bme-db-lab/szglab5-backend/commit/cb4131ce55346e1c7753c97d3def7c48e6d0c7a4
