### ISSUE TITLE
Tömörítés hiánya

### ISSUE THREAD

**Issue by dnet** [bme-db-lab/szglab5-backend#104]
#98 szerint Apache mögött proxy-zva fut a backend, ennek ellenére hiába küld az UA `Accept-Encoding` fejlécet, a `gzip`, `deflate` és `br` (Brotli) egyikét sem használja a szerver a válasz tömörítéséhez, pedig van válasz, amit gzip is nyolcadára (!) tudna tömöríteni, Brotli pedig tizedére is.

A linkelt ticket alapján @jmarton lehet illetékes, kérdés, hogy be van-e kapcsolva a `mod_deflate`, és ha igen, hogyan van konfigurálva. Nálam például a következő sor kiválóan gzipeli a kimenetet megfelelő `Accept-Encoding` fejléc megléte esetén reverse proxy felállásban is úgy, hogy a backend erről mit sem tud:

    AddOutputFilterByType DEFLATE application/json

**Comment by jmarton** [comment]
A `mod_defalte` ugyan be volt kapcsolva, de a default Debian konfig szerin a JSON-t nem tömörítette (a CSS-t igen, és az XML-t is tömörítette volna) . Bekapcsoltam, és nálam már tömörít (az API JSON válaszait gzip-pel, a CSS-t `br` segítségével).

@dnet köszi a javaslatot! Kérlek, hogy ellenőrizd, és ha rendben, zárd le.

```
<IfModule mod_deflate.c>
        <IfModule mod_filter.c>
                AddOutputFilterByType DEFLATE application/json
        </IfModule>
</IfModule>
```

**Comment by dnet** [comment]
Szuper! Amúgy mehet Brotli JSON-re is, csak azt most saját infrastruktúrán nem tudtam kipróbálni.
