### ISSUE TITLE
Model associations delete

### ISSUE THREAD

**Issue by Kisfejes** [bme-db-lab/szglab5-backend#11]
Add constrait to database, when you delete a test, delete all the associated questions too.
http://docs.sequelizejs.com/en/v3/docs/associations/ Something like onDelete: cascade

**Comment by jmarton** [comment]
In general I would not recommend cascading delete operations on the database level without maintaining proper history (which, in turn, is challenging). Doing so poses high risk on ad-hoc SQL operations.

On the API level, however, cascading delete should be a safe and convenient option to offer if it is made explicit in the API call.

**Comment by Kisfejes** [comment]
We are not using removing endpont, closing for now.
