### ISSUE TITLE
Generate model entities for semester start

### ISSUE THREAD

**Issue by Kisfejes** [bme-db-lab/szglab5-backend#14]
The task is to generate entities when semester starts from csv file source. 

Task list:
  - [x] Gather all type of sheet we can use Deadline: 2017.04.16
  - [x] Create example sheet each of this (with dummy data) Deadline: 2017.04.16
  - [x] Correlate each sheet and their fields, to model(s) and their attributes Deadline: 2017.04.16
  - [x] Provide CLI interface to generate model entities from these sheets Deadline: 2017.04.23
  - [x] Supply additional data (from json) to have the necessary records in the database for associations

**Comment by lordblendi** [comment]
For the init files: https://github.com/bme-db-lab/szglab5-main/issues/8

**Comment by Mordekk** [comment]
A lényegi része ennek az issuenak elkészült. A parseolás gond nélkül működik és az összes minta adatot betölti rendesen. Egy olyan gondom adódott még, hogy van olyan adat (pl kurzus kód, szemeszter azonosító, stb) amelyek nem lesznek xls-ben megadva, de asszociációnál szükség lenne rájuk. Ezekhez kellene majd valamilyen formában (pl json) még plusz adatokat szolgáltatni.

**Comment by lordblendi** [comment]
Mondd meg, hogy pontosan mely adatok kellenek meg es Sandor majd belerakja
az excel fajlba oket. Ha irsz egy listat, akkor modositom az init fajlokat.

**Comment by Mordekk** [comment]
Igazából olyan relatívan fix adatokról van szó, amiket nem is biztos hogy érdemes excelből parseolni. 
Pl EventTypes, DeliverableTypes, Courses, Semesters.
De ha úgy gondoljátok jobb lenne ha ezek is parseolva kerülnének be és nem egy json-ben (ahogy most megcsináltam) akkor írhatok egy pontos listát.
Erre igény lenne? Mert szerintem ennek jelentősége csak akkor lesz, ha tényleg több tárgy fog futni a rendszeren.

**Comment by lordblendi** [comment]
Irj kerlek egy pontos listat, hogy mi az, ami hianyzik. Foleg, mert valtozni fog a targy jovore, osszel es tavasszal kulonbozo targyak fognak futni.

**Comment by Mordekk** [comment]
Először szólnék, hogy Sándorral beszéltem még korábban, és 1-2 apróság módosult az init xlsx fájlokban.
A frissített verziók megtalálhatóak a backend db/seedData mappájában.
Ezen felül az ígért lista:
Courses: A futó kurzus [név és kódnév]
Semesters: Az éppen aktuális szemeszter [év és félév]
ExerciseCategories: A lehetséges feladat kategóriák (SQL, Oracle, SOAstb) [típus]
EventTemplates: A lehetséges esemény típusok (pl Labor alkalom) [cím, sorszám]
DeliverableTemplates: A lehetséges beadandó (értékelhető munka) típusai, pl Beugró, Git repo [leírás]

Ezekhez a modellekhez kellenének seed adatok. Célszerű lenne szerintem egy külön xlsx workbookba vagy sheetbe tenni, mert logikailag elkülönülnek a többi adattól.
