### ISSUE TITLE
Enhancement CLI with third party library

### ISSUE THREAD

**Issue by Kisfejes** [bme-db-lab/szglab5-backend#15]
Use this https://www.npmjs.com/package/cli library for CLI part of the application.

Task List:
- [x] get know the library
- [x] refactor the current CLI (/bin/laboradmin.js), to use this library Deadline: 2017.04.09

**Comment by Mordekk** [comment]
@Kisfejes commitoltam a saját branchemre (szdani), megnéznéd, hogy megfelel-e az elvárásaidnak?
