### ISSUE TITLE
Logging component

### ISSUE THREAD

**Issue by Kisfejes** [bme-db-lab/szglab5-backend#16]
Task is to improve logging mechanism of the backend.

Task list:
  - [x] Gather the functional requirements relevant to logging
  - [x] Design the configurability that fits the current config system
  - [x] Write own logger, or use a [third party][winston] **edit:** [winston] was selected
  - [x] Refactor the current codebase (replace all the console.log)

[winston]: https://github.com/winstonjs/winston

**Comment by jmarton** [comment]
It seems that [winston] was [selected][logging-ref] for logging.

Adding this decision to the first comment. Please correct if this is incorrect.

[logging-ref]: https://github.com/bme-db-lab/szglab5-backend/blob/master/package.json#L71
[winston]: https://github.com/winstonjs/winston
