### ISSUE TITLE
Required information for testing

### ISSUE THREAD

**Issue by zsambek** [bme-db-lab/szglab5-backend#19]
Szeretnénk segítséget kérni, hogy az alábbi funkciók teszteléséhez honnan tudunk adatot kapni az API-n keresztül, vagy pontosan melyik API szolgáltatná az ezekhez szükséges információkat?

 Listázás:
- 	Laborvezetői megjegyzés lekérdezése
- 	Mérésvezető személyének adatainak a lekérdezése
- 	Mérésvezető elérhetőségeinek lekérdezése
- 	Kezdeti jelszavak megtekintése
- 	Git remote URL lekérdezése

 Végleges értékelésnek a megjelenítése:
- 	Beugró jegy lekérdezése
- 	Jegyzőkönyvjegy lekérdezése
- 	Jegyzőkönyv riport lekérdezése
- 	Javító nevének lekérdezése
- 	Labor jegy lekérdezése
- 	Labor riport lekérdezése
- 	Megjegyzések lekérdezése

 Leadás:
- 	Jegyzőkönyv leadási határidejének megtekintése
- 	Minden címke listázása az adott labor repository-jából
- 	Végleges címke beállítása az címke listából

**Comment by Kisfejes** [comment]
A hallgató méréssel kapcsolatos funkciói:
- Mérések listázása: Megkeresni az adott user studentRegister-ét, azon keresztül lekérni az Event-eket
- Repository feltöltése: Eseményhez tartozó Deliverable frissitése (egy méréshez 2 típus tartozik)

A végpontokhoz autentikáció szükséges az auth/login-on  keresztül. A megkapott tokent utána minden kérés headerjébe bele kell rakni a kövekező formátumban:
Authorization: Bearer {token}
