### ISSUE TITLE
Méréssel kapcsolatos funkciók - Admin

### ISSUE THREAD

**Issue by zsambek** [bme-db-lab/szglab5-backend#21]
# Admin méréssel kapcsolatos funkciói:
##	Méréshelyek adatainak kezelése:

- [X] Méréshelyek listázása
ER-Path: Events
Endpoint: GET /events
- [X] Méréshelyek hozzáadása
ER-Path: Events
Endpoint: POST /events
- [X] Méréshelyek módosítása
ER-Path: Events
Endpoint: PATCH /events
- [X] Méréshelyek törlése
ER-Path: Events
Endpoint: DELETE /events
- [X] Méréshelyek és hallgatók összerendelése
ER-Path: Events/ StudentRegistrationId
Endpoint: PATCH /events/:id (attr: StudentRegistrationId)
- [X] Méréshelyek és mérésvezetők összerendelése
ER-Path: Events/ DemonstratorEmail
Endpoint: PATCH /events/:id (attr: DemonstratorEmail)
- [X] Méréshelyek és mérésidőpontok összerendelése
ER-Path: Events/ date
Endpoint: PATCH /events/:id (attr: date)

##	Feladattípusokkal kapcsolatos funkciók:
- [X] Feladattípus és értékelők összerendelése
ER-Path: Deliverables/ CorrectorName
Endpoint: PATCH /deliverables/:id (attr: CorrectorName)
- [X] Feladattípus és hallgatók összerendelése
ER-Path: Deliverables -> Events / StudentRegistrationId
Endpoint: PATCH /deliverables/:id/event (attr: StudentRegistrationId)

##	Határidők:
- [x] Hallgatói jegyzőkönyv leadásának határidejének módosítása
ER-Path: Deliverables / deadline
Endpoint: PATCH /deliverables/:id (attr: deadline)
- [X] Jegyzőkönyv értékelésének határidejének változtatása mérésenként, illetve globálisan
ER-Path: Deliverables / deadline
Endpoint: PATCH /deliverables/:id (attr: deadline)

##	Véglegesítés visszavonása:
- [X] Beugró esetén
ER-Path: Deliverables / finalized
Endpoint: PATCH /deliverables/:id (attr: finalized)
- [X] Jegyzőkönyv jegy esetén
ER-Path: Deliverables / finalized
Endpoint: PATCH /deliverables/:id (attr: finalized)
- [X] Végleges jegy esetén
ER-Path: Deliverables / finalized
Endpoint: PATCH /deliverables/:id (attr: finalized)

##	Beugrókkal kapcsolatos funkciók:

- [X] Új kérdés hozzáadása
ER-Path: TestQuestions
Endpoint: POST /test-questions
- [X] Kérdés módosítása
ER-Path: TestQuestions
Endpoint: PATCH /test-questions

**Comment by zsambek** [comment]
@VoidXH dev.seed.json-nal szeretném tesztelni a 
```
Hallgatói jegyzőkönyv leadásának határidejének módosítása
ER-Path: Deliverables / deadline
Endpoint: POST /deliverables/:id (attr: deadline)
```
Viszont, ha küldök egy postot, a {{url}}/deliverables/2-re, akkor azt a választ kapom, hogy `Endpoint not found: POST /deliverables/2`.
Ez egyébként a Body:
```
{
  "data": {
    "type": "deliverables",
    "attributes": {
      "deadline": "2017-03-30T12:11:17.576Z"
    }
  }
}
```
Köszi szépen a segítséged!

**Comment by VoidXH** [comment]
Bocs, elírtam, az PATCH, nem pedig POST.

**Comment by zsambek** [comment]
@VoidXH ha nem nagy gond, akkor tudsz írni egy-egy példát az `Új kérdés hozzáadása` és `Kérdés módosítása` végponthoz, hogy a body-nak hogy is kellene kinéznie? Köszi szépen!

**Comment by VoidXH** [comment]
@zsambek Mindkettőhöz jó:
`{
  "data": {
      "id": 1,
      "type": "TestQuestions",
      "attributes": {
        "text": "asd",
        "createdAt": "2017-05-17T23:26:05.673Z",
        "updatedAt": "2017-05-17T23:26:05.673Z",
        "QuestionTypeId": null,
        "TestId": null
      },
      "relationships": {
        "QuestionType": {
          "data": null
        },
        "Test": {
          "data": null
        }
      }
  }
}`
