### ISSUE TITLE
Méréssel kapcsolatos funkciók - Javító

### ISSUE THREAD

**Issue by zsambek** [bme-db-lab/szglab5-backend#23]
﻿# Javító méréssel kapcsolatos  funkciói:
- [ ] Javítók számának lekérdezése
Jelenleg nincs role kezelés -> postponed
- [ ] Javítók számának szűrése feladattípus szerint
Jelenleg nincs role kezelés -> postponed

## Mérések:
- [X]  Mérések listázása
ER-Path: Events
Endpoint: GET /events

### Mérések szűrése:
- [X] Téma szerint (Oracle, SQL, JDBC)
ER-Path: Events -> ExerciseSheets -> ExerciseCategories
Endpoint: GET /events?filter[exercisecat]=SQL
- [X] Hallgató szerint
ER-Path: Events / StudentRegistrationId
Endpoint: GET /events?filter[student]=1
- [X] Dátum szerint
ER-Path: Events / date
Endpoint: GET /events?filter[datestart]=2017-04-01&filter[dateend]=2018-01-11
- [X] Méréshely szerint
ER-Path: Events / location
Endpoint: GET /events?filter[location]=IL105
- [X] Mérésvezetők szerint
ER-Path: Events / DemonstratorEmail
Endpoint: GET /events?filter[demonstrator]=demonstrator@db.bme.hu

## Jegyzőkönyvek:
- [X] Jegyzőkönyvek listázása
ER-Path: Deliverables
Endpoint: GET /deliverables
- [X] Jegyzőkönyv leadásának ideje
Mit akarunk csinálni vele? Mindegy, mindent lehet.
ER-Path: Deliverables / deadline
Endpoint: GET/deliverables/:id (attr: deadline)
Endpoint: GET /deliverables?filter[deadlinestart]=2016-09-20&filter[deadlineend]=2016-09-30
Endpoint: PATCH /deliverables/:id (attr: deadline)
- [X] Jegyzőkönyv véglegesítésének kezdeményezése javítás alatt lévő állapotban is
ER-Path: Deliverables / finalized
Endpoint: PATCH /deliverables/:id (attr: finalized)

### Jegyzőkönyvek szűrése:
- [X] Feladattípus szerint
ER-Path: Deliverables / DeliverableTemplateId
Endpoint: GET /deliverables?filter[template]=1
- [X] Státusz szerint (javított, javítatlan, javítás alatt, véglegesített)
ER-Path: Deliverables / grade (null), grading, finalized
Endpoint: GET /deliverables/:id (attr: grade, grading, finalized)
- [X] Jegyzőkönyvre adott jegy
ER-Path: Deliverables / grade
Endpoint: GET /deliverables?filter[grade]=5
- [X] Jegyzőkönyv lefoglalása
ER-Path: Deliverables / grading
Endpoint: PATCH /deliverables/:id (attr: grading)
- [X] Jegyzőkönyv feloldása
ER-Path: Deliverables / grading
Endpoint: PATCH /deliverables/:id (attr: grading)
- [X] Git repository URL lekérése
ER-Path: Deliverables / url
Endpoint: GET /deliverables?filter[git]=http://gitlab.com/super_repo/
- [X] Leadási határidő
ER-Path: Deliverables / deadline
Endpoint: GET /deliverables?filter[deadlinestart]=2016-09-20&filter[deadlineend]=2016-09-30

## Jegyzőkönyv véglegesítése előtti funkciók
- [X] Érdemjegy módosítása a javító által
ER-Path: Deliverables / grade
Endpoint: PATCH /deliverables/:id (attr: grade)
- [X] Megjegyzés módosítása a javító által
ER-Path: Deliverables / comment
Endpoint: PATCH /deliverables/:id (attr: comment)
- [X] Megjegyzés törlése a javító által
ER-Path: Deliverables / comment
Endpoint: PATCH /deliverables/:id (attr: comment)
- [X] Érdemjegy módosítása másik javító által
ER-Path: Deliverables / grade
Endpoint: PATCH /deliverables/:id (attr: grade)
- [X] Megjegyzés módosítása másik javító által
ER-Path: Deliverables / comment
Endpoint: PATCH /deliverables/:id (attr: comment)
- [X] Megjegyzés törlése másik javító által
ER-Path: Deliverables / comment
Endpoint: PATCH /deliverables/:id (attr: comment)
- [X] Jegyzőkönyv véglegesítése
ER-Path: Deliverables / finalized
Endpoint: PATCH /deliverables/:id (attr: finalized)

## Adott jegyzőkönyvhöz kapcsolódó adatok lekérdezése:
- [X] Hallgató neve
ER-Path: Deliverables -> Events -> StudentRegistrations -> Users / displayName
Endpoint: GET /deliverables/:id/student (attr: displayName)
- [X] Hallgató Neptun-kódja
ER-Path: Deliverables -> Events -> StudentRegistrations -> Users / neptun
Endpoint: GET /deliverables/:id/student (attr: neptun)
- [X] Hallgató elérhetősége
ER-Path: Deliverables -> Events -> StudentRegistrations -> Users / email
Endpoint: GET /deliverables/:id/student (attr: email)
- [X] Téma (mérés)
ER-Path: Deliverables -> DeliverableTemplates / description
Endpoint: GET /deliverables/:id/template (attr: description)
- [X] Feladattípus
ER-Path: Deliverables -> DeliverableTemplates / type
Endpoint: GET /deliverables/:id/template (attr: type)
- [X] Mérés ideje
ER-Path: Deliverables -> Events / date
Endpoint: GET /deliverables/:id/event (attr: date)
- [X] Leadási határidő
ER-Path: Deliverables / deadline
Endpoint: GET /deliverables/:id (attr: deadline)
- [ ] Git repo végleges címkéje
- [X] Beadás ideje
ER-Path: Deliverables / submitteddate
Endpoint: GET /deliverables/:id (attr: submitteddate)
- [X] Beadás határidőn belül vagy kívül történt
ER-Path: Deliverables / submitteddate, deadline
Endpoint: GET /deliverables/:id (attr: submitteddate, deadline)
- [X] Érdemjegyek
ER-Path: Deliverables / grade
Endpoint: GET /deliverables/:id (attr: grade)
- [X] iMSc pont
ER-Path: Deliverables / imsc
Endpoint: GET /deliverables/:id (attr: imsc)
- [X] Megjegyzések
ER-Path: Deliverables / comment
Endpoint: GET /deliverables/:id (attr: comment)

**Comment by Kisfejes** [comment]
ER kérdések issue: https://github.com/bme-db-lab/szglab5-main/issues/10

**Comment by lordblendi** [comment]
A javitoknak a kovetkezokre van szuksege:
- szures:
  - meres tipusa szerint (oracle, jdbc, stb.)
  - ennel tobb szuresre nincs szuksegunk
- listazas adott meres tipushoz:
  - javitasra varo, de nem lefoglalt jkv-ek listazasa (csak a hatarido lejarta utan jelenhetnek meg a jkv-ek)
  - maga altal lefoglalt, de javitatlan jkv-ek
  - maga altal kijavitott jkv-ek
  - mas altal javitott jkv-ek
- megjelenites lista nezetben:
  - fentebbi lista jo

Egyeb funkciok:
- lefoglalt, de nem veglegesitett jegyzokonyv atadhato barmely masik javitonak


Kerdes:
"Jegyzőkönyv véglegesítése előtti funkciók" resznel a "masik javito altal" az mit takar?

**Comment by zsambek** [comment]
@Kisfejes 
Ehhez is elkészültek a teszt esetek.
A szglab5-test/use-cases/mender... postman-collection.json-ben vannak a teszt eseteik. :)
