### ISSUE TITLE
Méréssel kapcsolatos funkciók - Hallgató

### ISSUE THREAD

**Issue by zsambek** [bme-db-lab/szglab5-backend#24]
﻿# Hallgató méréssel kapcsolatos funkciói:
### Mérés adatainak megjelentése: 
- [x] Mérések helyszínének lekérdezése
ER-Path: Events / location
Endpoint: GET /events/:id ( attr: location )
- [x] Mérés időpontjának lekérdezése
ER-Path: Events / date
Endpoint: GET /events/:id ( attr: date )
- [x] Laborvezetői megjegyzés lekérdezése
ER-Path: Events / date
Endpoint: GET /events/:id (attr: comment )
- [x] Mérésvezető személyének adatainak a lekérdezése
ER-Path: Events <-> Users
Endpoint: GET /events/:id/demonstrator
- [x] Mérésvezető elérhetőségeinek lekérdezése
ER-Path: Events <-> Users
Endpoint: GET /events/:id/demonstrator
- [ ] Kezdeti jelszavak megtekintése
ER-ben ezek hol találhatóak?
- [x] Git remote URL lekérdezése
ER-Path: Deliverables / url
Endpoint: GET /deliverables/:id

### Végleges értékelésnek a megjelenítése:
- [x] Beugró jegy lekérdezése
ER-Path: Deliverables / grade
Endpoint: GET /deliverables/:id
- [x] Jegyzőkönyvjegy lekérdezése
ER-Path: Deliverables / grade
Endpoint: GET /deliverables/:id
- [x] Jegyzőkönyv riport lekérdezése
ER-Path: Deliverables / comment
Endpoint: GET /deliverables/:id
- [x] Javító nevének lekérdezése
ER-Path: Deliverables <-> Users
Endpoint: GET /deliverables/:id/corrector
- [X] Labor jegy lekérdezése
ER-Path: Deliverables / grade
Endpoint: GET /deliverables/:id
- [ ] Labor riport lekérdezése
ER-ben merre található?
- [ ] Értékelt Git címke lekérdezése
ER-ben merre található?
## Leadás:
- [x] Jegyzőkönyv leadási határidejének megtekintése
ER-Path: Deliverables / deadline
Endpoint: GET /deliverables/:id
- [ ] Minden címke listázása az adott labor repository-jából
- [ ] Végleges címke beállítása az címke listából

**Comment by jmarton** [comment]
@zsambek szép munka. Egy dolog: az értékelésre kijelölt git tag is lekérdezhető/megjelenítendő kell, hogy legyen a hallgató számára (akár maga választotta ki, akár másik szereplő vagy a rendszer)

**Comment by zsambek** [comment]
@jmarton Köszönjük szépen (@bkopy és én). 
Hozzáadtam egy `Értékelt Git címke lekérdezése` mezőt.

**Comment by Kisfejes** [comment]
Amik ki vannak pipálva azok a master-en már műkődnek.

**Comment by zsambek** [comment]
@Kisfejes elkészítettem a kipipáltakhoz a teszt eseteket, ha szeretnéd futtatni, akkor postmanbe be tudod őket importálni, mint collection. 
[use-cases/student-event-details.api.postman-collection.json](https://github.com/bme-db-lab/szglab5-test/blob/master/use-cases/student-event-details.api.postman-collection.json)
[use-cases/student-event-final-rating.api.postman-collection.json](https://github.com/bme-db-lab/szglab5-test/blob/master/use-cases/student-event-final-rating.api.postman-collection.json)
Ha minden igaz, akkor majd global environmnet variable-nek fel kell venni a saját url-ed (ahol futnak az endpointok), illetve egy üres token változót.

**Comment by zsambek** [comment]
@Kisfejes 
A többihez is elkészültek a teszt-esetek. A test/use-cases mappában megtalálod őket. postman-collection.json ez is.
