### ISSUE TITLE
Account generálások

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-backend#25]
Infrastruktúra és BE együttműködésben meg kellene tervezni, hogyan történjenek az account generálások. Felelős: @szaszm. Kérlek, hogy egyeztess BE csapattal.

## Generálni kell tudni ezeket

- [ ] laboradmin hozzáférés, ld. [init templates]
- [ ] linux shell szerver hozzáférés, belépés csak nyilvános kulccsal. A kulcs változása esetén ezt karban kell tartani
- [ ] gitlab user
- adatbázis user (a projekt szkópjában nincs benne)
- [ ] git repository (hallgatónként több, ahogy repository típusú deliverable van. Pótméréshez a félév vége felé külön event, külön deliverable példány, így külön git repository is készül)

### git repository

L. még: [gitlab api docs]

 - a hallgatói user *Developer* hozzáférést kapjon a hallgatói repo-hoz, így nincs jogosultsága átírni a git tageket. [gitlab jogosultságok]
 - az oktató minden hallgatói repo-ra *Reporter* jogot. Valószínűleg ezt érdemes csoport jogosultság alapján kiosztani.

### gitlab user (RFC)

L. még: [gitlab api docs]

A hallgatói user external user lesz, az oktatói nem external.

A web UI hozzáférést nem promotálnánk. Mivel a gitlab user létrehozáshoz kell email cím, azt `noreply-student+NEPTUN@db.bme.hu` email címmel hozhatnánk létre.

Az ssh kulcs változása esetén karban kell tartani az új usernél is

jelszó: a doksi szerint `PUT /users/:id` esetén:

> On password update, user will be forced to change it upon next login.

Ki kell próbálni, hogy a jelszó beállítása esetén a jelszavas ssh és https repository (és nem webUI) hozzáférés működik-e megváltoztatás nélkül.

 [init templates]: https://github.com/bme-db-lab/szglab5-main/tree/master/docs/init-templates
 [gitlab jogosultságok]: https://gitlab.db.bme.hu/help/user/permissions
 [gitlab api docs]: https://docs.gitlab.com/ce/api/users.html

**Comment by jmarton** [comment]
@szaszm mi a helyzet ezzel?

**Comment by Mordekk** [comment]
@szaszm és én közösen visszük az issuet, backend oldalról én támogatom meg azzal amire szüksége van. 

Ennek fényében arról szeretnénk információt kérni, hogy mi az elvárás, hogyan kapja meg a felhasználó az első jelszavát?

**Comment by szaszm** [comment]
@Mordekk elkezdte a backend oldali támogatás fejlesztését (pl. xls parser), én pedig péntek-vasárnap között megcsinálom az accountokat generáló scripteket. 
A linux shell hozzáférés helyik szerveren lesz, @jmarton ? Ha jól tudom, hogy nem általunk adminisztrált szerverre kapnak hozzáférést a hallgatók. Hogyan generálható egy felhasználó egy ilyen szerveren?
A gitlab instance telepítése nem olyan problémamentes, mint gondoltam, ezért nem sikerült még megcsinálni. Ezzel is a fent megjelölt időintervallumban tudok foglalkozni, illetve kell is, mivel az account generálás függősége a gitlab telepítés.

**Comment by jmarton** [comment]
@Mordekk a laboradminba a hallgatók címtáras bejelentkezéssel kellene, hogy bejussanak, így jelszó kiosztására nincs szükség. (a mostani rendszerben az első alkalommal nyomtatva adjuk ki ezeket)

@szaszm jól tudod, hogy eddig nem általunk adminisztrált linux shell szerveren mentek a mérések. A pótmérésen néhány csoport kísérletileg egy általam adminisztrált gépet használ, a `snail.db.bme.hu` szervert. További különbség, hogy a jelenlegi rendszerben jelszóval, a jövőben ssh nyilvános kulcssal lépnének be a hallgatók a shell szerverre.

Két lehetőség (valószínűleg van még sok), hogy

 1. valami PAM-trükk segítségével a laboradminban tárolt ssh nyilvános kulcshoz authentikál a shell szerver, és ha nem létezik, akkor sikeres PAM válasz esetén létrejön a linux user
 2. egy root által futtatott script létrehozza a usert. Ebben a megoldásban szükség lesz a nyilvános kulcsok frissítésére is, ha változna a laboradminban tárolt érték.

**Comment by Mordekk** [comment]
@jmatron és mi a helyzet az oktatókkal? Nekik is kell jelszó és ha jól tudom ők nem sibbolethel lépnek be.

**Comment by jmarton** [comment]
@Mordekk jogos. Az oktatók egy részének (nem mindenkinek) van címtáras azonosítója, de ők valóban beléphetnek jelszóval is. Mivel az e-mail címük ismert, egy email-alapú jelszó reset mechanizmus lehet számukra a megoldás.

**Comment by Kisfejes** [comment]
A gitlabos dolgokat backend oldalról viszem.
