### ISSUE TITLE
Account belepes vegpont

### ISSUE THREAD

**Issue by csutorasr** [bme-db-lab/szglab5-backend#26]
A login route csak egy tokennel ter vissza. Amire meg szukseg lenne:

* [ ] Felhasznalo jogkorei
* [x] Felhasznalo id-ja (sajat adatok lekerdezesehez)

**Comment by Kisfejes** [comment]
A jogkörök / szerepkörök egyenlőre nincsenek implementálva, a user id benne van a tokenben ( jwt decoder kell hozzá)

**Comment by Kisfejes** [comment]
A felhasználói jogkörök átmenetileg egy stringként kerülnek leadásra.
{
  ...
  role: "STUDENT"
  ...
}
