### ISSUE TITLE
Hallgato vegpontok egysegesites

### ISSUE THREAD

**Issue by csutorasr** [bme-db-lab/szglab5-backend#27]
A vegpontok neve ossze vissza vannak, az ember nem kepes ertemezni az adatot.

Pl: StudentRegistrations a kapcsolatnal a neve, de student-registrations helyett studentregistrations a vegpont neve.

Itt szerintem a studentRegistrations kapcsolattal student-registrations vegponttal lenne a jo.

**Comment by Kisfejes** [comment]
A végpontok összetett szavaknál '-' elválasztást kapnak a továbbiakban. pl(student-registrations)
