### ISSUE TITLE
Seed során hiba

### ISSUE THREAD

**Issue by zsambek** [bme-db-lab/szglab5-backend#29]
Hiba:

1.  `npm run cli:dev seed test.seed.json` vagy `npm run cli:dev seed dev.seed.json`
2.  ``` error: Seed failed: insert or update on table "StudentRegistrations" violates foreign key constraint "StudentRegistrations_UserId_fkey" ```

Van valamilyen ötletetek?

**Comment by Kisfejes** [comment]
Valószínű változott a modell, aminek már nem felelel meg felseedelni kivánt JSON

**Comment by zsambek** [comment]
Esetleg van nektek a dev.seed.json-ból olyan, amely logikailag ugyanazt tartalmazza, viszont illeszkedik az új modellre?

**Comment by Mordekk** [comment]
Használd az "npm run cli:dev init" parancsot. Elvileg nagyjából mindent feltölt, ha valami kell ami nincs mégsem benne, azt a dev.initbase.json-ben tudod hozzáadni.

**Comment by zsambek** [comment]
@Mordekk tudnál abban segíteni, hogy a dev.initbase.json-ben feltöltsem a test.seed.json-ban található adatokat is? Azért lenne fontos, mivel az API tesztek ezekre az adatokra épülnek, és az eddigi 45/45-es teszt  sikeresség arányból lett 5/45. Kipróbáltam már azt, hogy a test.seed.json-ban található elemeket átmásoltam a dev.initibase.json-ba, viszont akkor az alábbi hibát kapom: 
```
error: Init failed: null value in column "id" violates not-null constraint
```

Köszi szépen!

**Comment by Mordekk** [comment]
@zsambek Erre nagyon egyszerű a magyarázat, explicit meg kell adni az id kulcs értéket. A models mappában látható .js fájlok leírják hogy milyen modellhez milyen adattagok tartoznak.
Ha ezek alapján sem megy, akkor beszélhetünk slacken, vagy megpróbálhatom bemásolni neked azokat az adatokat úgy, hogy működjön.

**Comment by zsambek** [comment]
Megoldódott, @Mordekk megcsinálta, hogy a `test.seed.json` -t lehessen a régi módon is használni!
