### ISSUE TITLE
/users/:id hiba

### ISSUE THREAD

**Issue by csutorasr** [bme-db-lab/szglab5-backend#32]
Amikor a `/users/:id` vegpontra kerdezek le, akkor a kovetkezo hibat kapom:
`operator does not exist: character varying = integer`

A proglema blokkol, minden frontend elem hasznalja a vegpontot, mert minden a felhasznalohoz van kotve.

**Comment by jmarton** [comment]
Kapcsolódik #31 (talán ismétlés?)
