### ISSUE TITLE
AKÉP rendszer információ

### ISSUE THREAD

**Issue by Kisfejes** [bme-db-lab/szglab5-backend#34]
Az AKÉP rendszerről információ gyűjtés (információ, szükséges bemenet, formátum)

**Comment by Kisfejes** [comment]
EP: POST /sql
példa body: 
```
{
	"sqlText": "SELECT * FROM public.\"Users\" ORDER BY id ASC LIMIT 5"
}
```
példa válasz:
```
[
    [
        {
            "id": 1,
            "displayName": "Random Hallgato 1",
            "loginName": null,
            "password": "$2a$10$vlv5YUEp4RsLuk472x30NebwWfAcCju.bLcWMISzCvk8sVhoYy83C",
            "email": null,
            "sshPublicKey": null,
            "colorTheme": "blue-gray",
            "subscribedToMailList": null,
            "subscribedToEmailNotify": null,
            "role": null,
            "neptun": "NEPTUN1",
            "university": "BME",
            "email_official": null,
            "mobile": null,
            "title": null,
            "printSupport": null,
            "classroom": null,
            "spec": null,
            "exercises": null,
            "createdAt": "2017-07-09T09:23:19.174Z",
            "updatedAt": "2017-07-09T09:23:19.174Z",
            "OwnedExerciseId": null
        },
        {
            "id": 2,
            "displayName": "Random Hallgato 2",
            "loginName": null,
            "password": "$2a$10$dUJJxaxrWisA6mBGwOZT4OogDXfbihS4Qwgh6G/XYNdtaX6ChrI8O",
            "email": null,
            "sshPublicKey": null,
            "colorTheme": "blue-gray",
            "subscribedToMailList": null,
            "subscribedToEmailNotify": null,
            "role": null,
            "neptun": "NEPTUN2",
            "university": "BME",
            "email_official": null,
            "mobile": null,
            "title": null,
            "printSupport": null,
            "classroom": null,
            "spec": null,
            "exercises": null,
            "createdAt": "2017-07-09T09:23:19.296Z",
            "updatedAt": "2017-07-09T09:23:19.296Z",
            "OwnedExerciseId": null
        },
...
```

**Comment by jmarton** [comment]
AZ AKÉP FE integráción már dolgozott @csutorasr.

Az AKÉP BE integrációról tavasszal (2017-03-04) volt egy levélváltás, annak a lényegét idemásolom, kiegészítve egy triggerelő JSON sablonnal:

@jmarton:
> Az AKÉP integrációhoz egy mondat: TCP socketen keresztül kell elküldeni az értéklésre szánt csomagot az AKÉP-nek.
> 
> A válasz kétféleképpen jöhet:
> 
> 2a. ebben a socketben szinkron módon visszajön
> 
> 2b. aszinkron értékel, és az AKÉP leteszi az értékelését valahova (callback egyelőre nincs, de lehet egy konkrét értékelés státuszát lekérdezni az AKÉP-től, így egy promise/java Future-jellegű wrapper felépítése sem tűnik az AKÉP oldaláról támogathatatlannak - ezt egyelőre senki se vegye készpénznek, inkább csak egy kis betekintésnek)
> 
> Jelenleg az értékelési csomag metaadatai (feladattípus, hallgató Neptunkódja, futtató account típusa) mellett a hallgatói megoldás (.zip fájl) fájlrendszeri elérhetősége kerül átadásra. Tehát van fájlrendszer-link az AKÉP-ről a laboradminba. Pl.

```
{
  "ownerID":"<NEPTUN>",
  "exerciseID":"<FELADATSOR_SZAM>-<MERES PL: SOA>",
  "runUserGroup":"<normal|high>",
  "solutionZip":"<hallgatoi_munka.zip>"
}
```

> 
> Az új rendszerhez igazodva ez majd módosításra kerül, azaz pl. a git-ben levő megoldásra mutató referencia (git URL+commit id), illetve ha támogatunk fájlfeltöltős megoldást, akkor maga a fájl is a socketen utazna.
> 
> 
> (2a) esetén az értékelést tartalmazó XML jön vissza a socketen. 

@Kisfejes:
> Oké, a TCP socket/server kezelés a nodejs core library-k része, viszont lehet hogy hülye kérdés, de miért fapados, illetve miért nem jobb megoldás, hogyha a python script (AKÉP) ugyanazon a gépen / docker imagen van, és stdout-al kommunikálnak (illetve itt is játszhat a leteszi fájlba az eredményt, stdout-on csak azt jelzi hogy kész, vagy hiba).
> 
> És akkor a TCP-n alapuló kommunikáció helyett (aminek egy csomó előnye van, de itt szerintem overkill lenne):
> - Backend -> AKÉP: childprocess script hivással, paraméterezéssel
> - AKÉP -> Backend: 
>       - Jelzés ha kész/hiba: STDOUT
>       - Eredmény: STDOUT vagy File

@jmarton:
> a TCP socketes kommunikacio egy lazabb csatolast tesz lehetove a laboradmin es az AKEP kozott.
> 
> Az AKEP egy altalanos keretrendszer, nem adatb labor specifijus, megha itt szuletett is. A hallgatoi beadasokon tul hasznaljak az oktatok a teszt-leirasaik kiprobalasara is.
> 
> Van benne eroforrasgazdalkodas, aminek kereteben a master processz kiosztja, hogy melyik jegyzokonyv tesztje melyik adatbazis-felhasznaloval fusson. Ezt kar lenne a laboradmin szintjen kezelni.
> 
> Lehet, hogy ugyanazon a virtualis gepen fog menni, mint a laboradmin, de valoszinubb, hogy nem. Jobban szeretem, ha olyan szempontbol tiszta az image, hogy egyetlen funkciot kiszolgalo szoftverkornyezet van ott (pl. OS upgrade konnyebb igy)

**Comment by zsambek** [comment]
Nyikes Danival volt egy megbeszélésem az előző hét folyamán, ahol abban maradtunk, hogy az integráció úgy fog megvalósulni, hogy az AKÉP ugyanúgy külön fog működni, viszont hozzá lesz csatlakoztatva a Beadó rendszerhez.

Bővebben: 
Az integráció viszont úgy fog megvalósulni, hogy amikor a beadó rendszeren valaki véglegesíti az adott laborját, akkor az egyben egy trigger is lesz arra, hogy a beadó rendszer letöltse az adott felhasználó laborját, és egy előre megadott névkonvenció alapján (pl.: neptun/meres/feladatsor/.zip) elmenti egy mappába. 
Az AKÉP jelenleg is képes arra, hogy SSHFS-vel egy fájlrendszert felcsatlakoztasson magára, tehát ezt a mappát az AKÉP fel fogja csatolni magához, és folyton figyeli, hogy érkezett-e új leadott labor. Amennyiben igen, akkor kiértékeli. 
A beadó rendszerről úgy lenne megoldva az authorizáció, hogy a javító rákattint az Értékelt gombra a hallgató laborja mellett, ez utána átviszi őt az AKÉP oldalára úgy, hogy Cookie-ban átvisszük a session id-jét is. Utána az AKÉP visszakérdez a beadó rendszer felé, és attól függően, hogy tényleg érvényes vagy érvénytelen session id volt, betölti az AKÉP-et, vagy sem. 

Az eheti megbeszélésen még specifikáljuk a végpontokat @Kisfejes-sel, illetve azt is, hogy a többieknek ez megfelel-e.

**Comment by Kisfejes** [comment]
Info gyűjtés OK, kövi az implementálás
