### ISSUE TITLE
Levlista feliratkozás / leiratkozás

### ISSUE THREAD

**Issue by Kisfejes** [bme-db-lab/szglab5-backend#35]
A specifikáció szerint a felhasználók feliratkozhatnak egy maghatározott ( ? adatbATsch.bme.hu  ) listára. Az adatbázisban tároljuk a tényt, hogy valaki fel / le van iratkozva.

Egy ötlet a megoldásra:
A frontenden amikor a felhasználó átállitja a levlista feliratkozó switch-et, és utána rákattint a mentésre, akkor megkapja a backend a módosított értékeket, ami alapján elvégzi a fel és leiratkozást.

**Comment by jmarton** [comment]
A jelenlegi megoldás úgy néz ki, hogy egy sympa levlista [taglista forrás]ként használja a laboradmint.

Jelenleg konkrétan az `include_sql_query` az, amit használunk, de nem kizárt az `include_remote_file` használata sem.


[taglista forrás]: https://www.sympa.org/manual/parameters-data-sources

**Comment by szaszm** [comment]
Akkor ez azt jelenti, hogy adunk hozzaferest a sympanak az adatbazisunk megfelelo reszehez, es megadunk egy sql query-t, es nekunk mar csak egy flaget kell atbillenteni a beallitas valtozasakor, a tobbit eszreveszi a sympa. Jol ertem, @jmarton ?

**Comment by jmarton** [comment]
Jól érted, @szaszm. A sympa kb óránként lekérdezi a taglista adatforrást, és az alapján elvégzi a fel ill. leiratkoztatásokat.

A lista *az adatbázisok labor tárgyhoz* a `konzi.adatlabor@db.bme.hu`.

**Comment by jmarton** [comment]
Összelőttem, le is futott az első taglista-szinkronizáció.

Egyelőre azzal a feltételezéssel éltem az SQL megalkotásakor, hogy egyetlen tárgy egyetlen, aktuálisan futó szemeszterének adatai vannak a rendszerben:

A sympa levlista konfig snippet:

```
include_sql_query
db_type Pg
db_name foo
host foo-host-name
db_port 5432
user reader_user_name
passwd xxx
sql_query select distinct email from "Users" where "subscribedToMailList" = true and email is not null
```
