### ISSUE TITLE
Shibboleth integráció

### ISSUE THREAD

**Issue by Kisfejes** [bme-db-lab/szglab5-backend#39]
Shibboleth integrálása a rendszerbe, autentikáció + szükséges adatok elkérése, és mentése a megfelelő hallgatóhoz.

**Comment by jmarton** [comment]
Máködik a dev és az éles webszerveren a címtár login kezelése.

Már csak a BE támogatás kell hozzá (a `/api` path megkapja a shibboleth modultól az infókat), plusz egy link a FE-n, hogy belépés címtárral. Ennek megfelelően előrevettem a 2018 tavaszi milestonera.

**Comment by csutorasr** [comment]
Frontenden a link csak ki lett kommentelve, a formázás is megvan. Ha lesz link, akkor könnyedén lecserélhető.

**Comment by jmarton** [comment]
Köszi, @csutorasr. Ha jól értem, íme a két snippet:

https://github.com/bme-db-lab/szglab5-frontend/blob/988ee1f1505c5d847a9d1e1dbdfd165706b9921f/app/components/login-box.js#L42-L45

https://github.com/bme-db-lab/szglab5-frontend/blob/988ee1f1505c5d847a9d1e1dbdfd165706b9921f/app/templates/components/login-box.hbs#L2-L4
