### ISSUE TITLE
ADMIN funkciók

### ISSUE THREAD

**Issue by Kisfejes** [bme-db-lab/szglab5-backend#40]
1. Felhasználóval kapcsolatos folyamatok
* Felhasználó jelszó beállitása
- [x] BE PATCH /users/:id { newpwd: "", oldpwd: "" } megj.: Adminként nincs szükség az oldpwd-re
- [x] FE
* Új felhasználó felvétele
- [x] BE PATCH /users { loginName: "newuser", displayName: "New User", password: "12345" ... }
- [x] FE
* Felhasználó Jogosultságok megtekintése
- [x] BE GET /users/:id
- [x] FE
* Felhasználó Jogosultságok hozzáadása
- [x] BE
- [x] FE
* Felhasználó Jogosultságok törlése
- [x] BE
- [x] FE
* Felhasználó keresés: név GET http://localhost:7000/users?filter%5Bsearch%5D=laci&limit=10&offset=0
- [x] BE
- [x] FE
* Felhasználó keresés: user név GET http://localhost:7000/users?filter%5Bsearch%5D=laci&limit=10&offset=0
- [x] BE
- [x] FE
* Felhasználó keresés: user id GET http://localhost:7000/users?filter%5Bsearch%5D=laci&limit=10&offset=0
- [x] BE
- [x] FE
* Javítónak a javítandó feladatok típusának beállitása (duplikalva)
- [x] BE
- [x] FE
* sudo POST /auth/impersonate/ { userId: 1 }
- [x] BE
- [x] FE
2. Mérésekkel és mérésvezetőkkel kapcsolatos folyamatok
* méréshelyek (csoportok) listázás (Appointments lista)
- [ ] BE
- [ ] FE
* méréshelyek (csoportok) hozzáadás (Appointments)
- [ ] BE
- [ ] FE
* méréshelyek (csoportok) módosítás (Appointments)
- [ ] BE
- [ ] FE
* méréshelyek (csoportok) törlés (Appointments)
- [ ] BE
- [ ] FE
* méréshelyek és hallgatók összerendelése (StudentGroup modositas)
- [ ] BE
- [ ] FE
* méréshelyek és mérésvezetők összerendelése (StudentGroup staff relation)
- [ ] BE
- [ ] FE
* ~~méréshelyek és mérésidőpontok összerendelése~~ (Appoinmentsbe belekerult)
3. Feladattípusokkal kapcsolatos funkciók:
* ~~feladattípus és értékelők összerendelése (több--több)~~ (duplikalva 1.bol)
*  Generálás után: feladattípus és hallgatók összerendelése (Event -- ExerciseSheets)
- [ ] BE
- [ ] FE
* Generálás előtt: StudentRegistrations <-> ExerciseTypes
- [ ] BE
- [ ] FE
4. Eredményekhez, statisztikákhoz tartozó funkciók:
* Részletes eredmények listázása csoportonként
- [ ] BE
- [ ] FE
* Részletes eredmények listázása hallgatóként
- [ ] BE
- [ ] FE
* Összesített eredmények listázása csoportonként
- [ ] BE
- [ ] FE
* Összesített eredmények listázása hallgatóként
- [ ] BE
- [ ] FE
* Házi feladatok esetén a feladattípusonként a nem véglegesített jegyzőkönyvek számának listázása javítók szerint
- [ ] BE
- [ ] FE
* Lezáratlan mérésjegyek számának (van jegyzőkönyvjegy, de nincs laborjegy) listázása mérésvezetők szerint
- [ ] BE
- [ ] FE
* Javítók terheltségének listázása
- [ ] BE
- [ ] FE
* Eredmények exportálása CSV állományba
- [ ] BE
- [ ] FE
5. Határidők
* Hallgatói jegyzőkönyvek leadásának határidejének módosítása (1 hallgato) (deliverable deadline modositas)
- [ ] BE
- [ ] FE
* Hallgatói jegyzőkönyvek leadásának határidejének módosítása (1 csoport) (adott StudentGroup osszes)
- [ ] BE
- [ ] FE
* ~~Hallgatói jegyzőkönyvek leadásának határidejének módosítása (1 feladattipus)~~ Ertelmetlen, mert olyannak is modosithatja, akinek nem szeretne. (A-B het)
* Jegyzőkönyv értékelésének határidejének változtatása mérésenként **CSAK TEMPLATEBOL GENERALAS ELOTT**
- [ ] BE
- [ ] FE
* ~~Jegyzőkönyv értékelésének határidejének változtatása feladattipusonként~~ Ertelmetlennek tunik ez is.
- [ ] BE
- [ ] FE
6. Jegyzőkönyvek kezelése:
* Jegyzőkönyv archiválása (plágiumkereséshez) (minden adat lekerese minden repobol)
- [ ] BE
- [ ] FE
7. Hírek, hirdetmények kezelése:
* Hírek listázása
- [x] BE GET /news
- [x] FE
* Hír létrehozása
- [x] BE POST /news 
- [x] FE
* Hír szerkesztés
- [x] BE PATCH /news
- [x] FE
* Hír törlése
- [x] BE DELETE /news:id
- [x] FE
8. Véglegesítés visszavonása
* Beugró esetén (naplózás!)
- [ ] BE
- [ ] FE
* Jegyzőkönyv esetén (naplózás!)
- [ ] BE
- [ ] FE
* Végleges jegy esetén (naplózás!)
- [ ] BE
- [ ] FE
9. SQL szkriptek futtatása
- [x] BE POST /sql
- [x] FE
10. Beugrókkal kapcsolatos funkciók
* Új kérdés 
- [x] BE POST /questions
- [x] FE
* Kérdések listázása
- [x] BE GET /questions
- [x] FE
* Kérdés módosítása
- [x] BE PATCH /questions/:id
- [x] FE
* Kérdés törlése
- [x] BE DELETE /questions/:id
- [x] FE
* 4-7 kérdés kiválasztása és pdf létrehozás
- [x] BE  GET /generatePDF?questionId=2&questionId=1
- [x] FE

**Comment by csutorasr** [comment]
Uj letrehozasa vegpontoknal kell validacio.
