### ISSUE TITLE
Felev eleji generalas folyamata

### ISSUE THREAD

**Issue by csutorasr** [bme-db-lab/szglab5-backend#42]
##Szerintunk a generalas folyamata:

0. Userek mar felevvel adottak.
1. StudentGroups letrehozasa (Gyakcsoport/labcsoport)
2. EventTemplates letrehozasa (1.gyak/1.lab/2.gyak ... )
3. EventTemplates-hez DeliverableTemplates kotese (osszekottetes jelentese: 1.gyak beugroja, 1.lab beugroja, 1.lab jegyzokonyve, 1.lab vegjegye ...)
4. StudentGroups es EventTemplates osszekotese appointmentekkel. (A csoportokat beirjuk az egyes orakra. Osszkottetesek jelentese eddig: GY02-nek 3. beugroja kedden, L03-nak 5. jegyzokonyve szerdan)
5. EventTemplates es ExerciseCategories osszekotese (pl: 1. gyakon ORACLE a feladat, 2. gyakon SOA ...) (Osszekottetesek jelentese eddig: GY02-nek 3. SOA tipusu beugroja kedden van)
6. Users es ExerciseTypes osszekotese (pl: Nagy Pista a HAJO feladatot oldja, Kis Jozsef a RESZVENY feladatot oldja)
7. Events es Deliverables generalasa a felevre. (Osszekottetesek jelentese: Nagy Pista a L03-nak 1. jegyzokonyve, ami SOA tipusu, HAJO-22 feladat kedden oldja meg)

A 7. pontot az ev elejen szeretnenk generalni, vagy mindig, amikor ott tartunk az idovel csoportonkent?
(Ha folyamataban csoportonkent, akkor nincs szukseg csoportos deadline modositasra, de ha az ev elejen akkor van)

Kedd es szerda datumok is lehetnenek, csak a pelda kedveert vannak.

Ez igy rendben van?

**Comment by jmarton** [comment]
@csutorasr Nagyjából rendben van. Részletesen ld. a sorok között.

> 0. Userek mar felevvel adottak.

Ezt úgy kell érteni, hogy a bme-db-lab/szglab5-main#8-ban hivatkozott hallgató-listát már feldolgoztátok, azaz minden hallgatónak van korábbról vagy frissen készült user rekordja, és elkészült a studentregistrations bejegyzése is a tárgy aktuális futását jelölő semester rekordhoz?

Ugye rá lehet küldeni pótlólag is egy hallgató-listát a későbbi tárgyfelvevőkkel? Vagy őket UI-alapon, egyenként kell felvenni?


> 1. StudentGroups letrehozasa (Gyakcsoport/labcsoport)

Így van, ez is megy a hallgató lista alapján.

> 2. EventTemplates letrehozasa (1.gyak/1.lab/2.gyak ... )

stimmel.

> 3. EventTemplates-hez DeliverableTemplates kotese (osszekottetes jelentese: 1.gyak beugroja, 1.lab beugroja, 1.lab jegyzokonyve, 1.lab vegjegye ...)

Stimmel.

> 4. StudentGroups es EventTemplates osszekotese appointmentekkel. (A csoportokat beirjuk az egyes orakra. Osszkottetesek jelentese eddig: GY02-nek 3. beugroja kedden, L03-nak 5. jegyzokonyve szerdan)

Utaltál is rá: ezek valóban konkrét dátum+időpontok.

Az előző pontnál írottak szerint az appointment a labor vagy a gyakorlati foglalkozás időpontját mondja meg (hisz ez lesz az Event). Ez hagyományosan a beosztas-minta.xlsx *idopontok* fülén készül el.

> 5. EventTemplates es ExerciseCategories osszekotese (pl: 1. gyakon ORACLE a feladat, 2. gyakon SOA ...)

stimmel.

> 6. Users es ExerciseTypes osszekotese (pl: Nagy Pista a HAJO feladatot oldja, Kis Jozsef a RESZVENY feladatot oldja)
> 7. Events es Deliverables generalasa a felevre. (Osszekottetesek jelentese: Nagy Pista a L03-nak 1. jegyzokonyve, ami SOA tipusu, HAJO-22 feladat kedden oldja meg)

Itt egy kis félreértést érzek.

Az ER diagram nem jelez általában User és ExerciseType kapcsolatot. Azt mondja, hogy az Event és az ExerciseSheet között kell kialakítani a kapcsolatot.

Az ExerciseSheet az egy (ExerciseCategory, ExerciseType) páros, pl. (Oracle, HAJO), vagy (SOA, RÉSZVÉNY)

A tárgy adott félévi futásakor Nagy Pista ha a HAJO feladaton dolgozik, akkor az összes labor Event-jéhez a HAJO-ra vonatkozó ExerciseSheet-et rendelünk. Majd a pótmérésen kap mondjuk BETONOZÁS feladatot.



> A 7. pontot az ev elejen szeretnenk generalni, vagy mindig, amikor ott tartunk az idovel csoportonkent?

Az Event-eket a *nem pótmérésekre* vonatkozóan a félév elején szeretnénk generálni, hiszen a hallgató számára is ez alapján listázható, hogy melyik napokon lesz laborja. Pl. a hétfőiek programját az okt.23. fel fogja borítani, de a laboradminból pontosan fogja tudni, hogy okt. 23. helyett okt. 30. vagy nov. 6. lesz az ő napja.

Az Event-eket a *pótmérésekre* vonatkozóan majd a pótlási hét előtt kell generálni. Az annyiban tér el a félév elejitől, hogy a pótmérésre jogosultak bukott Event-jéhez kell majd egy másik ExerciseSheet-et kiadni ugyanazon ExerciseCategory-ban, tehát a Nagy Pista, aki HAJO-t csinált, és elbukta az Oracle labort, akkor az Oracle event-jéhez lesz egy retry event, ami az ExerciseSheet(Oracle, BETONOZAS) példányhoz lesz kötve.

A Deliverable-k generálásának időpontja többféleképpen is jó lehet. Generálható az Event generálásakor vagy azután nemsokkal aszinkron, de generálható akár az Event időpontja előtt, pl. hajnali 3:05-kor is.


> (Ha folyamataban csoportonkent, akkor nincs szukseg csoportos deadline modositasra, de ha az ev elejen akkor van)

A csoportos deadline módosítás az emélkeim szerint nem gyakori. Ha infrastruktúra probléma miatt van hosszabbítás, azt sokszor nem is vezetjük át a laboradminban, csak tudnak róla a hallgatók és a laborvezetők is. De valóban úgy szép, ha ez könnyen átvezethető a laboradminban is.

**Comment by Kisfejes** [comment]
> Itt egy kis félreértést érzek.
>
> Az ER diagram nem jelez általában User és ExerciseType kapcsolatot. Azt mondja, hogy az Event és az ExerciseSheet között kell kialakítani a kapcsolatot.
> 
> Az ExerciseSheet az egy (ExerciseCategory, ExerciseType) páros, pl. (Oracle, HAJO), vagy (SOA, RÉSZVÉNY)
> 
> A tárgy adott félévi futásakor Nagy Pista ha a HAJO feladaton dolgozik, akkor az összes labor Event-jéhez a HAJO-ra vonatkozó ExerciseSheet-et rendelünk. Majd a pótmérésen kap mondjuk BETONOZÁS feladatot.

Az ExerciseTypes-t és a StudentRegistrations-t szeretnénk összekötni, amikor egy adott Semester-t inicializálunk, akkor rendelünk mindegyikhez véletlenszerűen, ami majd később módosítható, viszont a generáláskor (Event példányok létrehozásánál), ez alapján tudunk hozzá ExerciseSheets-et rendelni.

**Comment by jmarton** [comment]
@Kisfejes rendben, köszönöm. Teljesen jogos, így stimmel!
