### ISSUE TITLE
AKÉP rendszer integráció

### ISSUE THREAD

**Issue by Kisfejes** [bme-db-lab/szglab5-backend#48]
Az AKÉP rendszer implementálása a tervek alapján

**Comment by csutorasr** [comment]
A frontend reszet megcsinalom. Elvileg egy gomb kell a javitonak ami egy linket tartalmaz.

**Comment by csutorasr** [comment]
A gomb hozzaadva: [commit](https://github.com/bme-db-lab/szglab5-frontend/commit/aad262da324bb7cd2ebb012318befa1e93e3528c).

Formatum: `https://ertekelo-dev.db.bme.hu/#AKEPView/{{user.neptun}}/{{event.EventTemplate.ExerciseCategory.type}}`

**Comment by Kisfejes** [comment]
Az AKEP rendszer integralasa sikeresen megtortent.
