### ISSUE TITLE
Adatbázis helyreállitás

### ISSUE THREAD

**Issue by Kisfejes** [bme-db-lab/szglab5-backend#49]
Kérdés, hogy ezt hogy szeretnénk megvalósítani, adott időközönként teljes backup az adatbázisról, illetve a backup óta végrehajtott módosító sql query-k tárolása?

**Comment by csutorasr** [comment]
Szerintem minden nap ejfelkor egy dump-ot kene csinalni az adatbazisrol. Ezt egy cron-jobbal meg lehet oldani. Az sqldump fajlok nevei lehetnenek a het napjai, es akkor 7 napra visszamenoleg lehetne visszaallitani az adatbazist.

**Comment by szaszm** [comment]
Hasonlora gondoltam, csak orankent, es esetleg mashova backupolassal, ha
lesz ra lehetoseg.

**Comment by szaszm** [comment]
Nincs jobb otletem, igy implementalom.

feljegyzes a holnapi onmagamnak:
- install script frissitese a megvaltozott postgresql configgal. (pg_hba.conf, postgresql.conf)
- crontab valtozas dokumentalasa, backup script feltoltese a main repoba

**Comment by szaszm** [comment]
@jmarton Szukseg lenne egy helyre, ahova menteni lehet a backup dumpokat. Ha a backup szervert gondoltad az aktiv tagnak, akkor a /var/backups/laboradmin mappabol tudja letolteni a dumpokat. Ha az alkalmazasszerver lenne az aktiv, akkor kellene egy leiras, hogy hova/hogyan lehet feltolteni a backup dumpot. A logokat feltetelezem, hogy nem backupoljuk.

**Comment by szaszm** [comment]
https://github.com/bme-db-lab/szglab5-main/commit/13052ee30c24c6cf12a88a2588a630f9620ba57d

**Comment by jmarton** [comment]
Ezen sokat gondolkodtam, és pillanatnyilag arra tendálok, hogy a backup szerver töltse le, amit kell.

Ugyanis ha a laboradmin szerver lenne az aktív tag (ami sokkal könnyebb), akkor ha valaki bejut a laboradmin gépre, akkor átjut a backup szerverre is, ami pedig nem jó.

Talán az lenne a legjobb, ha a backup szerver indítaná a backup scriptet ssh-n. A backup script kimenete egyetlen fájl, és azt közvetlenül elmenti a saját fájlrendszerére. A tömörítést is a backup szerver intézné a backup script meghívása során.

Ha a pgdump mellé más is kerülne, akkor pl. lehetne tar-olni, vagy lehetne két backup script: az egyik a pgdump-ot adja ki magából, a másik meg az egyebeket.

Mi a véleményed, @szaszm?

**Comment by szaszm** [comment]
Nekem jonak tunik. Igy csak a backup szervernek kellene ssh hozzaferest adni a backup mappahoz.

Jelenleg csak pgdump van, es az orankent (minden ora 0. perckor) a /var/backups/laboradmin/dump_YYYYMMDD_HHMM.dump fajlba kerul. 

Erre kellene egy scriptet irni a backup szerver reszere, ami mindezt intezi. Ezt nekem kellene megirnom, @jmarton ? Ha igen, akkor kellene egy pontosabb specifikacio. (Milyen idokozonkent masolja a backupokat, hova tegye a backup szerveren, milyen tomoritessel, milyen gyakran torolje a regi backupokat, stb.)
Ha nem, akkor csak egy ssh publikus kulcsra van szuksegem, aminek jogot adok a szerveren. A dev szerveren valo beallitas utan dokumentalom a valtoztatasokat.

**Comment by jmarton** [comment]
A régi backupok törlése egyelőre jó lesz kézzel.

A pgdump jó, láttam a scripted is. Annyi kellene pluszba, hogy tudjam úgy meghívni a scriptet, hogy az stdout-ra teszi a dump-ot.

Tehát nem a backup location alatt elkészült fájlokat szeretném letölteni (rsync-el egyszerű lenne, de ha korrumpálódik egy mentés, akkor azt is átvenné az rsync, ami nem jó).

Helyette a mentőszerver kezdeményezi a backup műveletet, és intézi a tárolást, tömörítést. Felraktam a `.fecske-backup-publikus-kulcs` fájlba a fecske-dev root home-ba a nyilvános kulcsot.

Ettől még az, hogy egy helyi cron is menti, nagyon jó.

**Comment by jmarton** [comment]
@szaszm módosítottam a backup scriptet a dev gépen, h a helyi példány xz-vel kerüljön tömörítésre

**Comment by jmarton** [comment]
elkészült a cron a mentőszerveren: minden óra 16 perckor meghívja a backup scriptet, és az eredményét elmenti.

Egyelőre a dev szerveren hívja a mentőscriptet, de amint kész a prod gép, átirányítom.

**Comment by jmarton** [comment]
Bekapcsoltam a prod gépen is a db remote mentést: minde óra 29 perckor fut, és helyben meg remote-ban is leteszi.

**Comment by jmarton** [comment]
Bekapcsoltam a prod gépről a `backend/files` rsync-mentését ugyanúgy az óra:29-kor futó remote cron-ban.

Kikapcsoltam a dev gép remote postgreSQL mentését.
