### ISSUE TITLE
Feladatlap generálás

### ISSUE THREAD

**Issue by Kisfejes** [bme-db-lab/szglab5-backend#50]
Szükség van egy külső rendszer integrálására, amivel feladatlapot lehet generálni.
Első körben összegyűjteni a szükséges információt:
- Megismerni a külső rendszert: mi az input / output, hogy tudjuk futtatni
- Milyen interface-t biztositsunk a laboradminon keresztül az inputhoz, illetve hogy lehet utána hozzáférni az output-hoz

**Comment by csutorasr** [comment]
Esetlegesen a sajat pdf generalo nem lenne erre egy jobb megoldas?

**Comment by szaszm** [comment]
Ha mar lenyegeben meg van irva, akkor nem kene ujrairni IMO. Persze ugy sem
lenne bonyolult a pdf resze, de nem hiszem, hogy odt-t is akarunk jsbol
generalni.

**Comment by jmarton** [comment]
A pdf generálást a mostani rendszerhez is egy mozdulat, és néhány gigányi texlive függőség hozzátenni. A generátor közvetlenül ugyanis markdown-t állít elő, és abból pandoc készíti a többi verziót.

Volt már ilyen javaslat, sőt, komoly kontribúció is jött mellé. Két okból nem kapcsoltam eddig be:
 - (ez a fontosabb) eddig Mono alapú frontend volt, ami kicsit törékeny és instabil, és nem akartam mögé tenni még egy óriási texlive feldolgozást.
 - tipikusan a tördelésen javítottak a mérésvezetők, ahhoz pedig szerkeszthető változat kell.

**Comment by jmarton** [comment]
Felraktam a *-dev* gépre a generálót egy új, `handout` nevű user alá.

A git root-ban van egy README.md, abban a *Generátorok / build információk* szakasz szól róla.

Ezeket telepítettem:
```shell
# apt-get install scons pandoc openjdk-8-jre-headless
```

De az első generálási élmény ennyiből meg is van, ahol `handout-sample` a *csomagnév*:
```shell
$ cd; cd *; scons HD=handout-sample ; ls -la handout/handout-sample.*
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.
-rw-r--r-- 1 handout handout 23505 Aug 30 16:38 handout/handout-sample.html
-rw-r--r-- 1 handout handout 16679 Aug 30 16:38 handout/handout-sample.md
-rw-r--r-- 1 handout handout 25085 Aug 30 16:38 handout/handout-sample.odt
-rw-r--r-- 1 handout handout  1501 Aug 30 16:38 handout/handout-sample.xml
```

@szaszm, a kulcsodat bemásoltam. Egyelőre állítottam be, hogy frissítse a repository-t, amiből dolgozik, de a `.ssh/config` alatt van a magic hozzá.

**Comment by szaszm** [comment]
@jmarton: Pontosan melyik git rootban van ez a README.md megfelelo szakasszal?

**Comment by jmarton** [comment]
@szaszm: a fecske-dev feladatlapgeneralas celjara letrehozott user homejaba leklonozozz gitroot-ban.

**Comment by szaszm** [comment]
@jmarton:
```
java -cp lib/saxon9he.jar net.sf.saxon.Transform -s:handout/handout-sample.xml -xsl:handout/handout.xsl -o:handout/handout-sample.md                          
Error: Could not find or load main class net.sf.saxon.Transform
```
ez milyen csomaggal kerulne fel?
