### ISSUE TITLE
SQL log

### ISSUE THREAD

**Issue by Kisfejes** [bme-db-lab/szglab5-backend#53]
SQL log kiegészités, hogy ki miatt fut az adott sql query.
jsonAPI-n keresztül: A beautentikált felhasználó
CLI-on keresztül: cli user

**Comment by szaszm** [comment]
https://github.com/bme-db-lab/szglab5-main/commit/13052ee30c24c6cf12a88a2588a630f9620ba57d

**Comment by Kisfejes** [comment]
Minden végponthivásnál ha autentikált a felhasználó, akkor logolásra kerül
