### ISSUE TITLE
Javító / beadandó kiválasztása

### ISSUE THREAD

**Issue by Kisfejes** [bme-db-lab/szglab5-backend#55]
Javító beadandó kiválasztása javitásra:
- pagination
- filter:
  - excerciseCategoryId -> deliverableTemplateId
  - lefoglaltat ne mutassa ( BE )
  - ExerciseType, csak amihez ért ( BE )
  - csak azokat mutassa aminek lejárt a határideje
Javító által lefoglalt beadandók listázása, frontend flag-et állit
  - végleges / nem végleges 

BE megj.: update alapján DESC sorbarendezés (csak saját lekérdezésnél)

**Comment by Kisfejes** [comment]
excerciseCategoryId:
filter[exerciseCategoryId]=2
deliverableTemplateId:
filter[deliverableTemplateId]=1
lefoglalt / szabad
filter[isFree]=true
filter[isFree]=false
ExerciseType, csak amihez ért:
még nincs kész
végleges:
filter[finalized]=true
filter[finalized]=false

**Comment by csutorasr** [comment]
Mind implementalva lett, frontenddel osszekotve
