### ISSUE TITLE
https a prod gépre

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-backend#56]
Elkészült a valódi https cert a prod gépre. Telepítsd lsz. a webszerverre.

A fecske.db.bme.hu címre érvényes, és a fecske-prod gépen a `/root/https-cert` alá felmásoltam.

Felvettem egy CNAME bejegyzést is: `fecske -> fecske-prod`

**Comment by szaszm** [comment]
Elkeszult, lasd: https://fecske.db.bme.hu
Ez a konfiguracio eleg altalanos (nem projekt-specifikus), igy nem erzem szuksegesnek dokumentalni.
Ha maskepp gondolod, nyisd ujra az issuet!
