### ISSUE TITLE
hibák tőlem nektek.

### ISSUE THREAD

**Issue by bkopy** [bme-db-lab/szglab5-backend#59]
Márkkal egyeztetve ide dobálom amiket találtam.

ha user list-en vagyok nem tudok visszamenni listazasra mert az aktiv menupontot hiaba nyomom meg nem tolti ujra
ha viszont belemegyek egy felhasznaloba akkor a back gomb hatasara elorrol kezdhetem a show more nyomogatást
a kereső mezőben a név benne marad vagy neptun amit beirtam, de a hozza tartozo lista nem

NEWS-t létrehozok nem ír semmi választ nem dob el az oldalról csak létrehoz egy hírt

user roles-nál demonstrator kilóg

**Comment by csutorasr** [comment]
Vissza gomb hatasara azert kell ujra tolteni, mert ha valtoztattal adatot, akkor az igy kint is befrissul, es nem a regi adat marad. Egyben lekerni az elozoleg 10 oldalon at betoltott paginationt kicsit hulyeseg lenne, mert akkor minek pagination. A megoldas lehet, hogy a vissza gombnal egy oldalt betolt, igy ha a szures elegge pontos volt, akkor a felhasznalodat visszakapod.

Az issuekat letrehozom, miutan leokezod a fenti megoldasomat.

**Comment by lordblendi** [comment]
A keresesi mezoket szerintem resetalni kellene, ha visszamesz a keresesre. En inkabb ket kulon esetre bontanam:
- ha a detailed view-bol nyomsz back gombot, akkor maradjon ott a kereses eredmenye es a keresesi szo
- ha ranyomsz a list menupontra (ezt nem csak a user keresesnel, hanem barhol mashol), akkor toltse be az adott menupont default allapotat (ami jelen esetben ures keresesi mezo tablazat nelkul)

Illetve en a button mellett engedelyeznem az enterre valo keresest.

Ezenkivul, kereses ne legyen case sensitive 
- t eseten talalja meg a T-t
- u eseten talalja meg az ű-t


Egyeb:
- news letrahozasanal menjen vissza a news listazasara (immaron frissitett tablazatnak kellene megjelennie)
- a UI most felig angol, felig magyar. Szerintem el kellene donteni, hogy melyiket hasznaljuk, vagy beepiteni egy nyelv valasztot

**Comment by Kisfejes** [comment]
Ezeket szét kéne szedni kisebb issuek-ra, illetve szétdobálni a backend és a frontend között.

**Comment by csutorasr** [comment]
Én ezeket már szétszedtem és javítottam is.

**Comment by Kisfejes** [comment]
Akkor zárható?
