### ISSUE TITLE
File extension

### ISSUE THREAD

**Issue by csutorasr** [bme-db-lab/szglab5-backend#60]
Sajnos a download attribute [nem igazan tamogatott](http://caniuse.com/#feat=download).

A megoldas az lenne, hogy a `/deliverables/:id/download` vegpont `307 Temporary Redirect` -tel (igy minden HTTP/1.1-es bongeszovel mukodne, mert a POST data-t ujrakuldi) iranyitana at a `/deliverables/:id/download/:filename` vegpontra. A `filename` parameter barmi lehet, akkor is a legutoljara feltoltott fajlt adja vissza. Ertelemszeruen, ha a `hello.zip`-et toltottem fel, akkor a `/deliverables/:id/download/hellop.zip`-re iranyit at, ahol a fajlnev helyes, es a fajl letoltheto.

**Comment by Kisfejes** [comment]
Átirányitással megoldva
