### ISSUE TITLE
Hallgató áthelyezése másik laborba

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-backend#61]
Van felület a hallgató áthelyezésére?

A dev-en oktato4-ként nem találtam meg. #22 szerint a backend talán tudja, de #45 elbizonytalanít.

**Comment by csutorasr** [comment]
Erre sajnos nincs lehetoseg. Ehhez ER model modositasra lenne szukseg. (Nagyon sok a redundans adat jelenleg, ennek csokkentesevel ez megoldhato lenne)

Gondoltam, hogy egy issuet felveszek ra, de belathato idon nem tudtuk volna abszolvalni, mert a seed-et modositani kellett volna nagyban hozza.

**Comment by Kisfejes** [comment]
Ehhez valószínű CLI parancs lesz, végpontra és frontend részre már nincs idő.

A kérdésem, hogy mit értünk áthelyezés alatt, másik csoportba? Vagy csak 1 alkalomra? Itt azt kell átgondolni még, hogy a már legenerált eventekben mit és hogyan kell módosítani.

**Comment by jmarton** [comment]
Hallgató alkalmi csoportcseréje: a hallgató mér máskor. Tehát egy konkrét event rekordban módosítandó: helyszín, dátum, oktató. A dátum módosítása pedig viszi magával a Deliverable-ben levő határidőt (ebbe a tervezéskor nem gondoltam bele, ez igényelhet némi hackelést).

**Comment by csutorasr** [comment]
Én annó úgy gondoltam, hogy egy új entitás kell class neven. Egy event a classhoz tartozik, ott van benne, hogy mikor és hol van az óra. Egy classhoz tartozna classdeliverable, ami a leadás határidejét tartalmazná és a deliverables-hez csatlakozna.

Generáláskor most az appointmentsbol lesz event ideje és event templatebol a tobbi adat hozzá. Ezen lépés szétbontásával lehetne megoldani a problémát.

**Comment by jmarton** [comment]
@csutorasr igazad van, hogy ezt a konkrét feladatot kényelmesebben lehetne megoldani az adatmodell efféle kiegészítésével. De pl. egyedi feladat konzultációja esetén nem értelmezett a class. Persze ebben a tárgyban nincs ilyen, de a modell megalkotásakor igyekeztünk általánosan gondolni.

**Comment by csutorasr** [comment]
Ebben az esetben CustomEvent entitásra is szükség van, ez az óráktól függetlenül hozható létre. Vagy egy class-t létrehozni, amiben csak ő van benne, és így kap időpontot.

@Kisfejes A cli tool is jó, de ott van az SQL menü is erre a célokra.

**Comment by jmarton** [comment]
CLI már van, thx to @Kisfejes .
Commitok: 859a5b6597b1ef3a3dd0a197a069d48c1e62ecef 042f76810f1db230700d4db83e6c2ae585621c8e e0e8b20b0fb23d60e235a76ab15a35df5009447f 1d2f9bdeab5ac9ebc4e4bd2eef2b44bd68d107ff 927007260d3064ad5653c20d55cf947e2a420f5f

```shell
backend@linux:~$ npm run cli:prod sng
```

**Comment by jmarton** [comment]
Mivel már CLI van, a  folytatást (FE-re kivezetés) v1.1 nice to have-re állítottam.

**Comment by jmarton** [comment]
Elkészült a fbb78eb84dede13344035ec5f261eb8bb776e639 commitban és a bme-db-lab/szglab5-frontend#125 PR-ben.
