### ISSUE TITLE
Szures

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-backend#62]
User szures (es barmilyen mas szures) jo lenne, ha nem lenne case sensitive se kis-nagy beture, se ekezetre.

Tehat mukodjon ugy, hogy:
- `lev`-re jelenjen meg minden Levente
- `nor`-ra a Nóra

**Comment by Kisfejes** [comment]
Az ékezet egy fokkal bonyolultabb, de a kis-nagy betű érzékenység kész.
commit: a666a1bff749d0e4e8d4e0393e4e4a2d6749f5b6

**Comment by csutorasr** [comment]
[Ez](https://www.npmjs.com/package/remove-accents) a package megoldja a problémát. A másik oldalról a postgre unaccent függvénye oldhatja meg. (Ez akár mind2 oldalon használható) Ha a sebesség kicsi, akkor az npm package-dzsel vegyél fel egy unaccentName attribútumot az egyedhalmazon, és állítsd be őket kézzel, az materializálva segíti a keresést.

**Comment by Kisfejes** [comment]
Kesz
