### ISSUE TITLE
Generált jelszavakban ne legyenek nyomtatásban összetéveszthető karakterek

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-backend#63]
Ne adjunk a hallgatók semmilyen jelszavába `O0` és `lI1` karaktereket.

Ld. funk.spec: https://github.com/bme-db-lab/szglab5-main/tree/master/docs/funkcionalis-specifikacio#%C3%81ltal%C3%A1nos-elv%C3%A1r%C3%A1sok

**Comment by jmarton** [comment]
quick win: excludeSimilarCharacters itt: https://www.npmjs.com/package/generate-password

**Comment by Kisfejes** [comment]
fixed
