### ISSUE TITLE
Hallgató-feladattípus elosztás legyen egyenletes

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-backend#64]
Az adatbázis feltöltésekor az egyes, aktív feladattípusok lehetőleg kb ugyanannyi hallgatónak legyenek kiosztva.

Viszont jól definiálni kell, hogyan lehet géppel jól felismerni és megvalósítani, hiszen az idegen nyelvű feladattípusok ez alól kivételek.

Idén az adatbázis inicializálásakor még nem voltak meg az angol nyelvű feladatlapok, ezért sem került elő az angol-nem angol eloszlási probléma 2017. őszén.

**Comment by gajdos** [comment]
A problema pontos algoritmikus megoldasat nem ismerem, de nem valoszinu, hogy NP teljes a feladat :-) Azt is tudom, hogy G. Bence a regi laboradminban +/- 1 pontossaggal egyenletesen dobta szet a feladattipusokat a hallgatok kozott. Meg arra is figyelt, hogy egyetlen laborcsoportban minden feladattipus megjelenjen. Lehet, hogy csak meg kell kerdezni ot :-)

**Comment by jmarton** [comment]
@gbence ?

**Comment by gbence** [comment]
A legegyszerűbb megoldás az, hogy a hallgatói csoportok kialakítását követően valamilyen rendezés szerint (pl. a csoportokon iterálva, azon belül pedig a hallgatókon iterálva) egy folyamat sorban, egyenletesen beosztja a feladattípusokat.

Pl. ha az alábbi csoportok és hallgatók vannak (a hallgatók vezetékneveinek az első betűjét jelöltem):

1. csoport: A, C, D
2. csoport: B, E, H
3. csoport: F, G

...akkor egy jó beosztás az alábbi -- 4 feladattípusra, amelyek a 21, 22, 23 és 24-es feladattípusok:

1. csoport: A(21), C(22), D(23)
2. csoport: B(24), E(21), H(22)
3. csoport: F(23), G(24)

Ez csoporton belül is különböző feladattípusokat eredményez és nagyjából egyenletesen osztja el a hallgatókat is.

**Comment by Kisfejes** [comment]
Elkészült a CLI parancs, ami Bence algoritmusát (köszönet érte) használva újraosztja a feladattipusokat.
