### ISSUE TITLE
Imsc pontok mozgatasa

### ISSUE THREAD

**Issue by csutorasr** [bme-db-lab/szglab5-backend#66]
Az imsc pontok az eventhez tartoznak es nem a deliverable-hez. Frontenden a kodot modositottam, ha backenden megvan, akkor frissitsetek.

[Ebben az issueban](https://github.com/bme-db-lab/szglab5-frontend/issues/39) van rola szo.

**Comment by Kisfejes** [comment]
fixed, élesitésre vár

**Comment by jmarton** [comment]
bme-db-lab/szglab5-frontend#39 miatt újranyitom. Onnan az adatmodellt érintő részt ide is leírva:

1. nem minden Deliverables példányhoz kell iMSc pont. Pl. beugróhoz biztosan nem. A legszebb az lenne, ha a DeliverableTemplates példány határozhatná ezt meg.
2. az iMSc pont az adatbázisban lehessen null (a Deliverables.imsc jelenleg not null default 0)
3. az új Events.imsc mező jónak tűnik,

**Comment by Kisfejes** [comment]
Egyenlőre az lett a gyors megoldás, hogy az events-re és a deliverables-re is raktunk imsc-t
