### ISSUE TITLE
Kesve beadas

### ISSUE THREAD

**Issue by csutorasr** [bme-db-lab/szglab5-backend#68]
A kesve beadas lehetseges.

Diakoknak. [Itt van](https://github.com/bme-db-lab/szglab5-frontend/blob/83d851250b88dcf76cf2f93f8fafaf353ef21f66/app/models/deliverable.js#L25-L28), hogy a frontend hogyan szamolja az idot.

**Comment by Kisfejes** [comment]
A backend fogadja a későn leadott jegyzőkönyvet is
