### ISSUE TITLE
[PILOT] Endpointok

### ISSUE THREAD

**Issue by Kisfejes** [bme-db-lab/szglab5-backend#7]
Endpointok hozzáigazitása az EmberJS elvárásaihoz + JSON API

**Comment by csutorasr** [comment]
A CORS megint gaz a legujabb dev lehuzasa utan.
Hibauzenet:
![image](https://cloud.githubusercontent.com/assets/6360699/24326032/a34489e4-11a5-11e7-9d3f-32ad5a47ccfa.png)

**Comment by Kisfejes** [comment]
fixed

**Comment by csutorasr** [comment]
A JSON API nem jo, mert displayName-t kuld display-name kulcs(hash) helyett az objectben. Kerlek javitsd ezeket. (Vagy ne legyenek kis-nagybetus adatok.

**Comment by Kisfejes** [comment]
Alapból camelCase-el küldöm vissza, illetve az adatbázisban is igy vannak tárolva az összetett attribútumok.

A JSON API specifikációban nem találtam erre vonatkozó szabályt, hogy az attríbutumoknak camelCase-t vagy snake-case-t kell használnia.

Rárakhatok még egy réteget ami a camelCase-ből konvertál, viszont a kérdés hogy ehhez nem tudna igazodni a frontend?

**Comment by csutorasr** [comment]
De, a frontendet atalakitottam.
(Ugy volt, hogy szoljak, ha az embernek nem jo valami, ezert tettem)

**Comment by lordblendi** [comment]
@Kisfejes Csak ajanlaskent ott van a dasherize a naming/2. Pontnal: http://jsonapi.org/recommendations/

Az Ember emliti, hogy o dasherize-t var el: https://guides.emberjs.com/v2.12.0/models/customizing-serializers/
Ha lentebb gorgettek, ott latszik, hogy a jsonapiserializert felul lehet csapni. ( @csutorasr  igy csinaltad? Meg nem pusholtal, igy nem latom a commitok kozott.) 


Alapvetoen azt mondom ez nem szep dolog, ugyhogy ha belefer, akkor orulnek meg egy retegnek. Ha egyaltalan nem fer bele, akkor igazodjon a frontend.

Viszont: amint ezen modositas mellett sem lehet megetetni a jsonapi valaszt a frontenddel (pl a modellek tipusa a valaszban snake_case vagy camelCase?) es amiatt manualisan kene a valasz jsont feldogozni (holott ezt a modell megtenne helyes formatum eseten), akkor viszont a backendnel implementalni kell a hianyzo reteget. Ugyanis: MVC-ben gondolkodunk frontend szinten is es nem VC-ben.

**Comment by csutorasr** [comment]
[Pusholtam](https://github.com/bme-db-lab/szglab5-frontend/blob/dev/app/serializers/application.js) es megoldottam.

**Comment by Kisfejes** [comment]
Azért választottam a camelCase-t, mert igy van tárolva és az ORM-el igy tudom könnyeb használni:
user['display-name'] helyett user.displayName

Szivesen rárakok egy réteget a válasznál, hogy ezeket átalakitsa, csak úgy éreztem hogy ezt a frontenden könyebben meg lehet oldani.

**Comment by lordblendi** [comment]
Csak akkor, ha belefer az idobe. Amig nem lesz belole problema, szerintem maradhat a camelCase.
