### ISSUE TITLE
laboradmin jegyzőkönyv feltöltése

### ISSUE THREAD

**Issue by bkopy** [bme-db-lab/szglab5-backend#71]
A jelenlegi szerintem még mindig nem a legmegfelelőbb. Most azután is fel tudnak tölteni új jegyzőkönyvet, miután a javító értékelte a laborjukat (vagy lefoglalta értékelésre). Ez szerintem továbbra sem egy jó megoldás, főleg ha a fájlok nem verziókezelve kerülnek mentésre. 

by: Kanyó Krisztián

**Comment by Kisfejes** [comment]
Véglegesités után nem engedélyezett a hallgatónak a feltöltés
