### ISSUE TITLE
javítási statisztika API végpont

### ISSUE THREAD

**Issue by bkopy** [bme-db-lab/szglab5-backend#72]
> nem sikerult ilyet talalnom, pedig a tapasztalatok szerint nagy szukseg van ra, hiszen ennek alapjan tudom – es kell is... – osztokelni az egyes javitokat a folyamatos javitasra.
> Hasonloan szukseges lenne a laborvezetoi jegy veglegesitesi statisztika is.
SAndor

egy olyan végpont létrehozása, melyről tud a frontend ilyen jellegű adatokat megjeleníteni ha jól értettem az Adminnak

**Comment by csutorasr** [comment]
Mar vannak meglevo vegpontok. Annak a mintajara kene folytatni az egeszet.

A vegpontok neveit majd legyeszi sorold fel ide.

**Comment by Kisfejes** [comment]
Sándorral való egyeztetés után:
-(1) Javitók, Admin: Képet kapjanak a javitás állásáról, meg tudják tekiteni a saját feladattipusokhoz tartozó beadott fájlok javitási állapotát (foglalt - javitó neve/szabad, véglegesitett/nem véglegesitett, jegy, imsc, határidő, feltöltés ideje)
-(2) Admin: mérésvezetők mérések -> info arról, hogy egy adott mérésen csoportonként hány véglegesitett jegy van, esetleg a jegyek eloszlásáról
-(3) Admin: Javítók terheltsége, összesitett statisztika, hogy hány kijavitott jegyzőkönyv tartozik egy javitóhoz

A következő végpontokat fogom megvalósitani:
(1)
GET /statistics/deliverables?eventTemplateId=1&exerciseTypeId=3
query paraméterek: 
- eventTemplateId: csak az adott eventTemplateId-s beadandókat küldi le REQ
- exerciseTypeId: csak az adott exerciseTypeId-s beadandókat küldi le
- asCorrector (asCorrector=true): csak a bejelentkezett felhasználóhoz rendszer exercise-okat küldi le (javitónál jól jöhet)

megj.: 
 - amit kötelező küldeni: (eventTemplateId) && (exerciseTypeId || asCorrector)
 - a file attribútumnál leküldöm az id-t, ott valami ilyesmit kéne csinálni belőle: $API_BASE_URL/download/:id
response body: 
```
{
  headers: ['id', 'name', 'neptun', 'exercise', 'labor', 'file', 'description', 'deadline', 'submittedDate', 'grade', 'imsc', 'finalized', 'corrector'],
  data: [
   {
     id: 0,
     name: 'Tuturu pumpuru',
     ...
   },
   ...
 ]
}
```

(2)
In progress
(3)
In progress
