### ISSUE TITLE
Deliverables tipusok nevenek angolra cserelese

### ISSUE THREAD

**Issue by csutorasr** [bme-db-lab/szglab5-backend#74]
Az uj angol felulet miatt most

> Jegyzőkönyv grade:

jelenik meg az oldalon.

**Comment by Kisfejes** [comment]
Mi az angol megfelelője a jegyzőkönyvnek?

**Comment by lordblendi** [comment]
Report, nem?

**Comment by Kisfejes** [comment]
Cseréltem a DeliverablesTemplates-ekben a description mezőt "Report"-ra
