### ISSUE TITLE
jegyzőkönyvfogadás

### ISSUE THREAD

**Issue by bkopy** [bme-db-lab/szglab5-backend#77]
> Fel tudnátok készíteni a laboradmin rendszert a 2. laborhoz a NEPTUN-2-CSOPKOD.pdf formátumú jegyzpkönyvek fogadására?
> Illetve az angolos csoportom, akiket Márk nem rég vitt fel, C12A kóddal fognak jegyzőkönyveket feltölteni (NEPTUN-1-C12A.pdf és hasonlók), ezt a csoportkódot tudnátok legalizálni? 
Levi

**Comment by jmarton** [comment]
Bocs, nem kerestem ki a BE issue-t. Ld. bme-db-lab/szglab5-frontend#78

**Comment by Kisfejes** [comment]
Státusz: kommunikáció folyamatban Levivel

**Comment by Kisfejes** [comment]
félreértés volt, zárom az issue-t
