### ISSUE TITLE
[PILOT] Modell

### ISSUE THREAD

**Issue by Kisfejes** [bme-db-lab/szglab5-backend#8]
A pilothoz szükséges modellek (Test, TestQuestion, QuestionType) javítása

**Comment by lordblendi** [comment]
Most akkor hogy vannak a modellek? A fent leirt haromnak az [itt https://github.com/bme-db-lab/szglab5-backend/tree/dev/models](https://github.com/bme-db-lab/szglab5-backend/tree/dev/models) levo harom nem teljesen felel meg. Es ha jol latom, van, ahol a kapcsolatnak csak az egyik iranya van definialva.

**Comment by Kisfejes** [comment]
Közben át lettek nevezve, (Test, Question, QuestionType), nincs még teljesen kész, ma estére (22:00) tudom igérni a végleges modelleket, illetve a még kimaradt végpontokat.

**Comment by gbence** [comment]
Kódban légyszi írjátok a modellt angolul, így: `model`
