### ISSUE TITLE
késés

### ISSUE THREAD

**Issue by bkopy** [bme-db-lab/szglab5-backend#83]
Azert irok mert egy eleg fura jelenseggel talalkoztunk ma.
A hallgatomnak eppen be akartam irni a jegyet labvezetokent, es azt
lattam, hogy ez szerepel nala a deadline-nal (elso kep): tehat 1 nap
es 19 perc keses.

Kozben kiderult, hogy az ertekelonel nem ekkora kesest jelez a
rendszer, hanem 0 nap es 19 percet, ez lathato a 2. kepen.

Na most en nem ertem hogy ez mitol van, a labor szept. 27-en volt
16:15-tol 18:00-ig. Tehat meg a 16:00-s deadline is kicsit fura,
hiszen akkor meg el sem kezdodott a labor. De igy labvezkent nagyon
nehez lesz figyelni a keseseket ha ez ilyen marad a rendszerben.

**Comment by Kisfejes** [comment]
A késést azokon az oldalon a frontend számolja, a deadline a laborkezdés + 1 nap-ból jön ki.

**Comment by lordblendi** [comment]
Igy van, a kesest valoban a frontend szamolja. Mostmar egysegesitetve, orakban irjuk ki. Kiirtam egy issue-t arra, hogy a perc is jelenjen meg: https://github.com/bme-db-lab/szglab5-frontend/issues/98

**Comment by Kisfejes** [comment]
mivel frontend issue, zarom a BE issue-t
