### ISSUE TITLE
Csoportváltás (sng parancs) törli a Deliverable tartalmát és még pár dolgot

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-backend#86]
Amikor hallgatót áthelyezünk másik csoportba, akkor a méréshez tartozó Deliverable példányok tartalma és az esetleges javítói értékelés is törlésre kerül a javítótól és a laborvezetőtől kapott jeggyel együtt (a laborvezetői megjegyzés nem kerül türlésre, ha jól látom).

A csoportáthelyezésnek csak a csoportra, helyszínre, időpontra, határidőre és demonstrátorra vonatkozó dolgokat kellene érintenie, és a *laborvezetői véglegesítést* visszavonni. Megjegyzést és beadást törölni nem szabad.

A probléma akkor merült fel, amikor csoportcsere utólagos bejegyzésére került sor utólagos, adminisztrátori jegyzőkönyv-beadás után.

A figyelemfelhívásért köszönet @missvarhegyi !

**Comment by Kisfejes** [comment]
reset-grades beallitas (flag) hozzaadva a parancshoz, aminek a default erteke false. Ha megis szeretnenk resetelni a labor illetve beadando jegyeket, akkor:
`npm run cli:prod -- sng --reset-grades`

**Comment by jmarton** [comment]
Emlékeim szerint ez teljesen elkészült. HA mégsem, kérlek, hogy nyisd újra, @Kisfejes
