### ISSUE TITLE
Oktatói gárda neptun kódjainak felvitele

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-backend#93]
A címtáras azonosításhoz (l. #39) kapcsolódóan szükséges a laborvezetők és a javítók neptun kódja is a rendszerbe.

Ennek két része van:

- [ ] legyen benne az inicializáló XLS-ben (@gajdos)
- [x] töltődjön be az adatbázisba (@Kisfejes) [PR](https://github.com/bme-db-lab/szglab5-backend/pull/97)

**Comment by gajdos** [comment]
OK, vettem, rajta vagyok, de a varatlanul megnott letszam miatt meg a napokban is ujabb demonstratorokat toborzok, ezert a lista alighanem csak az elso heten lesz teljes. Segitseg az, ha kuldok egy elozetes listat?

**Comment by jmarton** [comment]
Köszi, @gajdos, nem érdemes előzetes listát készíteni. A lényeg az, hogy a félévet inicializáló fájlban a labvezek fülön, ahol az oktatói gárda előrhetőségei szerepelnek, legyen ott a Neptun kód is.

**Comment by gajdos** [comment]
Reszemrol OK. A repo beosztas-minta.xls-be az F oszlopba fog kerulni a Neptun kod.

**Comment by jmarton** [comment]
ez már egy ideje rendben megtörténik, ezért lezárom.
